### ISSUE TITLE
Accessing the Documentation page results in a 404

### ISSUE THREAD

**Issue by moyerr** [Kitura/Swift-SMTP#112]
When I navigate to the documentation URL linked in the README, I get a 404 error. Link for reference:

https://ibm-swift.github.io/Swift-SMTP/

**Comment by mbarnach** [comment]
This should be fixed by PR #111 once merged. Thanks for pointing it out.
For reference, and if you need it, the doc is at: https://kitura.github.io/Swift-SMTP/

**Comment by dannys42** [comment]
@moyerr This should be resolved now.

**Comment by moyerr** [comment]
Thank you!
